---
  - hosts: app
    become: true
    vars:
      fav:
        fruit: mango
    roles:
      - { role: apache, tags: www}
      - { role: php, tags: ['www', 'php']}
      - frontend
    tags:
        - frontend
      